
C = {
"k": "\uec21",
"kqh": "\uec21", ####
"g": "\ued1c",
"gqh": "\uee60",
"ch": "\ueaa2", #######
"chqh": "\ueaa2",
"j": "\ueb88", #######
"jqh": "\uedcb", ########
"T": "\ued98",
"t": "\ued90",
"Tqh": "\uee82",
"tqh": "\uee80",
"D": "\ued68",
"d": "\uee00",
"Dqh": "\ueb40",
"dqh": "\ueb46",
"N": "\uee38",
"n": "\uee38",
"p": "\ueb88",
"pqh": "\uee93", ######
"b": "\ued60", ####
"bqh": "\ued84",
"m": "\ueae0",
"y": "\ued70", ######
"Y": "\ued70",
"r": "\uea48",
"l": "\uec35",
"v": "\uec35", #######\ue938
"V": "\ued60",
"sqh": "\uecb1",
"S": "\uecb1",
"s": "\uea20",
"h": "\uee40",
"L": "\uee00",
#########
"kqS": "\uee65",
"kqSqh": "\uee76",
"kqsqh": "\uee72",
"dqnqy": "\ued30",
"gqnqy": "\ued91",
"sqhqr": "\ued13",
"Qk": "\uecec",
"Qkqh": "\uec59",
"Qg": "\ueb1c",
"Qj": "\ueae1",
"QP": "\ueab2",
"QD": "\ue9fb",
"Qy": "\ue986",
"Qn": "\ue96e",
"Qr": "\uec59",
"QL": "\uec85",
"QDqh": "\uefb2",
"Qv": "\uedd4",
"Zg": "\uedea",
"Zj": "\ued72",
"ZD": "\ued50",
"Zb": "\uecee",
"DqDqA": "\uece6",
"ZHA": "\uecc0",
"JYqA": "\uec87",
"ZK": "\uebfe"
}

v = {
"aa": "\ueb5d",
"a": "\ueb5d",
"i": "\ueb10",
"ii": "\ueb11",
"ee": "\ueb5d",
"u": "\ueb5d",
"uu": "\ueb5d",
"oo": "\ueb10",
"e": "\ueb10",
"ai": "\ueb11",
"o": "\ueb5d",
"au": "\ueb5d",
"ou": "\ueb5d",
"aE": "\ueb10",
"aO": "\ueb11",
"AO": "",
"AE": "",
"zau": "\ueb5d",
"zo": "\ueb10",
"ze": "\ueb5d",
"": "\ueb5d",
"": "\ueb5d",
"": "\ueb5d",
"": "\ueb5d",
"": "\ueb5d",
"": "\ueb5d",
"Rri": "\ueb5d",
"RrI": "\ueb5d",
"Lqlqi": "\ueb5d",
"LqlqI": "\ueb5d"
}

V = {
"a": "\ueb5b",
"aa": "\ueb5b",
"A": "\ueb5b",
"AA": "\ueb5b",
"i": "\ueb5b",
"ii": "\ueb11",
"I": "\ueb11",
"II": "\ueb5b",
"ee": "\ueb10",
"u": "\ueb5b",
"uu": "\ueb5b",
"U": "\ueb5b",
"UU": "\ueb5b",
"oo": "\ueb5b",
"e": "\ueb10",
"ai": "\ueb11",
"E": "\ueb5b",
"EE": "\ueb5b",
"aE": "\ueb5b",
"o": "\ueb5b",
"O": "\ueb5b",
"au": "\ueb5b",
"AU": "\ueb5b", #####
"ou": "\ueb5b",
"RRi": "\ueb5b",
"RRI": "\ueb5b",
"LqLqi": "\ueb5b",
"LqLqI": "\ueb5b",
"zAU": "\ueb10",
"zO": "\ueb10",
"zEE": "\ueb5b",
"zA": "\ueb5b",
"zau": "\ueb5b",
"zo": "\ueb5b",
"ze": "\ueb5b",
"": "\ueb5b",
"": "\ueb5b",
"": "\ueb5b",
"": "\ueb5b",
"AO": "\ueb11",
"AE": "\ueb10",
"aE": "",
"aO": ""
}

misc = {
"M": "\uee70",
"MM": "\uee70",
"q": "\u200C",
".N": "\uee70",
" ": " ",
".": ".",
"f": " ",
"ff": " ",
"": "\ue970",
"": "\ue971",
"0": "\ue966",
"1": "\ue908",
"2": "\ue910",
"3": "\ue920",
"4": "\ue940",
"5": "\ue950",
"6": "\ue960",
"7": "\ue96d",
"8": "\ue96e",
"9": "\ue96f",
"om": " ",
"OM": " ",
"AUM": " ",
"W": "\u200d",
"w": "\u200c",
"P": "\uec50",
"G": "\uec8c",
"J": "\uecc2",
"K": "\ueac4",
"X": "\ued5c",
"B": "\ued9a",
"x": "\uedd6",
"F": "\uee2c",
"H": "\ueea1",
}
